djangoProject7/urls.py
from django.contrib import admin
from django.urls import path, include

from shop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('', include('shop.urls'))
]

shop/urls.py
from django.urls import path

from shop.views import MyHomePage, ProductDetailView, ProfileView, AddToBasketView, RemoveFromBasketView, BasketView, \
    OrderAddressView, OrderPaymentView, OrderSuccessView, OrderDetailView

urlpatterns = [
    path('', MyHomePage.as_view(), name='home'),
    path('product/<int:product_id>/', ProductDetailView.as_view(), name='product_detail'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('add-to-basket/', AddToBasketView.as_view(), name='add_to_basket'),
    path('remove-item/', RemoveFromBasketView.as_view(), name='remove_from_basket'),
    path('basket/', BasketView.as_view(), name='basket'),
    path('order-address/', OrderAddressView.as_view(), name='order_address'),
    path('order-payment/', OrderPaymentView.as_view(), name='order_payment'),
    path('order-success/', OrderSuccessView.as_view(), name='order_success'),
    path('order/<int:order_id>/', OrderDetailView.as_view(), name='order_detail')
]

shop/models.py
# Create your models here.

from django import forms
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomerManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        if password is not None:
            user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)


class Customer(AbstractUser):
    customer_id = models.AutoField("ID", primary_key=True)
    email = models.EmailField(unique=True, null=True)
    first_name = models.CharField("First Name", max_length=128)
    last_name = models.CharField("Last Name", max_length=128)

    country = models.CharField("Country", max_length=128, default='')
    city = models.CharField("City", max_length=128, default='')
    house = models.CharField("House", max_length=128, default='')
    street = models.CharField("Street", max_length=128, default='')
    room = models.CharField("Room", max_length=128, default='')

    card_number = models.CharField("Card number", max_length=128, default='', null=True)
    card_date = models.CharField("Card date", max_length=7, null=True, default=None)
    card_cvv = models.CharField("Card cvv", max_length=128, default='', null=True)
    phone = models.CharField("Phone", max_length=128, default='', null=True)

    username = models.CharField(max_length=150, unique=True, default='')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomerManager()

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)


class Goods(models.Model):
    order_id = models.AutoField("ID", primary_key=True)
    product = models.CharField("Product", max_length=128)
    price = models.DecimalField("Price", max_digits=10, decimal_places=2, default=0)
    product_description = models.CharField("Product description", max_length=1024, default='')
    image = models.ImageField("Image", upload_to='static/img/', default='https://via.placeholder.com/150', blank=True,
                              null=True)
    age = models.CharField("Age", max_length=128, default='')
    taste = models.CharField("Taste", max_length=128, default='')
    producer = models.CharField("Producer", max_length=128, default='')
    product_class = models.CharField("Product class", max_length=128, default='')
    features = models.CharField("Features", max_length=1024, default='')
    quantity = models.IntegerField("Quantity", default=5)
    CATEGORY_CHOICES = [
        ('cat', 'Cat'),
        ('dog', 'Dog'),
        ('parrot', 'Parrot'),
    ]
    category = models.CharField("Category", max_length=50, choices=CATEGORY_CHOICES)

    def __str__(self):
        return '%s %s' % (self.order_id, self.product)


class Basket(models.Model):
    basket_id = models.AutoField("ID", primary_key=True)
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    items = models.ManyToManyField('Goods', through='BasketItem')
    basket_session = models.CharField("Basket session", max_length=128, default='')
    status = models.CharField("Basket session", max_length=128, default='CREATED')
    created_at = models.DateTimeField(auto_now_add=True)
    last_reserved_status_date = models.DateTimeField("Last status date", null=True, blank=True)


class Order(models.Model):
    order_id = models.AutoField("ID", primary_key=True)
    basket = models.OneToOneField(Basket, on_delete=models.CASCADE)
    order_datetime = models.DateTimeField("Order Date and Time", auto_now_add=True)
    confirmation_code = models.CharField("Confirmation Code", max_length=128)
    confirmation_status = models.BooleanField("Confirmation Status", default=False)

    country = models.CharField("Country", max_length=128, default='')
    city = models.CharField("City", max_length=128, default='')
    house = models.CharField("House", max_length=128, default='')
    street = models.CharField("Street", max_length=128, default='')
    room = models.CharField("Room", max_length=128, default='')

    card_number = models.CharField("Card number", max_length=128, default='', null=True)
    card_date = models.CharField("Card date", max_length=7, null=True, default=None)
    card_cvv = models.CharField("Card cvv", max_length=128, default='', null=True)
    phone = models.CharField("Phone", max_length=128, default='', null=True)


class BasketItem(models.Model):
    basket = models.ForeignKey(Basket, on_delete=models.CASCADE)
    goods = models.ForeignKey('Goods', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)


class CustomerCreationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput, max_length=128,
                               error_messages={'required': _("Пароль должен содержать максимум 128 символов")})
    email = forms.EmailField(label=_("Email"), max_length=128,
                             error_messages={'unique': _("Пользователь с таким email уже зарегистрирован"),
                                             'required': _("Email должeн содержать максимум 128 символов")})
    first_name = forms.CharField(label=_("First Name"), max_length=128,
                                 error_messages={'required': _("Фамилия должна содержать максимум 128 символов")})
    last_name = forms.CharField(label=_("Last Name"), max_length=128,
                                error_messages={'required': _("Имя должно содержать максимум 128 символов")})

    class Meta:
        model = Customer
        fields = ('email', 'first_name', 'last_name', 'password')

templates/basket.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Basket</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<header class="header">
    <nav class="navigation">
        <div class="info-block d-flex align-items-center flex-row">
            <div class="logo-block"><a href="/" class="logo-link"></a></div>
            <div class="footer-links">
                <a href="#" class="footer-link">О магазине</a>
                <a href="#" class="footer-link">Контакты</a>
            </div>
        </div>
        <div class="links-div d-flex">
            <div class="d-flex align-items-center icon-block">
                <i class="header-basket-icon header-auth"></i>
                {% if user.is_authenticated %}
                    <a class="nav-links" href="/basket/">Корзина</a>
                {% else %}
                    <a class="nav-links" href="/accounts/login">Корзина</a>
                {% endif %}
            </div>
            <div class="d-flex align-items-center icon-block">
                {% if user.is_authenticated %}
                    <i class="header-lk-icon header-auth"></i>
                    <a class="nav-links" href="/profile">Личный кабинет</a>
                {% else %}
                    <i class="header-auth-icon header-auth"></i>
                    <a class="nav-links" href="/accounts/login">Вход / Регистрация</a>
                {% endif %}
            </div>
        </div>
    </nav>
</header>

<main>
    <section>
        <div class="container">
            {% if basket_items|length == 0 %}
                <h2>Моя корзина</h2>
                <h4 class="m-0 mt-5">Корзина пуста</h4>
            {% else %}
                <h2 class="mb-4">Моя корзина</h2>
                <div class="basket-nav">
                    <ul class="ul-basket-nav list-unstyled d-flex flex-row">
                        <li class="li-basket-nav">
                            <span class="nav-icon">1</span>
                            <a href="/basket/" class="a-basket-nav active">Корзина</a>
                        </li>
                        <li class="li-basket-nav">
                            <span class="nav-icon">2</span>
                            <span class="a-basket-nav">Доставка</span>
                        </li>
                        <li class="li-basket-nav">
                            <span class="nav-icon">3</span>
                            <span class="a-basket-nav">Оплата</span>
                        </li>
                        <li class="li-basket-nav">
                            <span class="nav-icon">4</span>
                            <span class="a-basket-nav">Спасибо!</span>
                        </li>
                    </ul>
                </div>
                {% for item in basket_items %}
                    <div class="row align-items-center card-custom">
                        <div class="col-md-2">
                            <a href="{% url 'product_detail' product_id=item.goods.order_id %}">
                                <img class="product-image" src="{{ item.goods.image.url }}" alt="Product Image">
                            </a>
                        </div>
                        <div class="col-md-5">
                            <span>{{ item.goods.product }}. {{ item.goods.product_description }} </span>
                        </div>
                        <div class="col-md-2 d-flex flex-row justify-content-around align-items-center">
                            <form method="post" action="{% url 'basket' %}">
                                {% csrf_token %}
                                <input type="hidden" name="action" value="add">
                                <input type="hidden" name="item_id" value="{{ item.id }}">
                                <button type="submit" class="btn btn-basket btn-plus"
                                        {% if basket.status == 'RESERVED' %} disabled {% endif %}>+
                                </button>
                            </form>

                            <span>{{ item.quantity }}</span>

                            <form method="post" action="{% url 'basket' %}">
                                {% csrf_token %}
                                <input type="hidden" name="action" value="remove">
                                <input type="hidden" name="item_id" value="{{ item.id }}">
                                <button type="submit" class="btn btn-basket btn-minus"
                                        {% if basket.status == 'RESERVED' %} disabled {% endif %}>-
                                </button>
                            </form>
                        </div>
                        <div class="col-md-2">
                            <span>{{ item.total_price }} р./{{ item.quantity }} шт</span>
                        </div>
                        <div class="col-md-1">
                            <form method="post" action="{% url 'basket' %}">
                                {% csrf_token %}
                                <input type="hidden" name="action" value="delete">
                                <input type="hidden" name="item_id" value="{{ item.id }}">
                                <button type="submit" {% if basket.status == 'RESERVED' %} disabled {% endif %}>
                                    <i class="fas fa-trash"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                {% endfor %}
                {% if messages and basket.status != 'RESERVED' %}
                    <ul class="messages list-unstyled">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }} alert alert-danger"
                                                     style="color: red" {% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {% if basket.status == 'RESERVED' %}
                    <div class="d-flex flex-row align-items-center justify-content-around">
                        <h4 class="m-0">Товары в корзине зарезервированы, для того, чтобы изменять корзину - снимите резерв</h4>
                        <form method="post" action="{% url 'basket' %}">
                            {% csrf_token %}
                            <input type="hidden" name="action" value="reset-reserve">
                            <button type="submit" class="btn basket-button">Снять резерв<i
                                    class="fas fa-shopping-basket"></i>
                            </button>
                        </form>
                    </div>
                {% endif %}
                <div class="row align-items-center my-5 justify-content-between">
                    <div class="col-md-auto d-flex flex-row">
                        <div class="col-md-auto mx-4">
                            <h2 class="m-0">
                                Итого: {{ total_basket_price }} Руб.
                            </h2>
                        </div>
                        <div class="col-md-auto">
                            <form method="post" action="{% url 'basket' %}">
                                {% csrf_token %}
                                <input type="hidden" name="action" value="clear">
                                <button type="submit" class="btn bg-secondary"
                                        {% if basket.status == 'RESERVED' %} disabled {% endif %}>Очистить корзину <i
                                        class="fas fa-trash"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                    <div class="col-auto">
                        <a href="/order-address/" class="btn basket-button">{% if basket.status != 'RESERVED' %} Начать
                            оформление {% else %} Продолжить оформление {% endif %}</a>
                    </div>
                </div>
            {% endif %}
        </div>
    </section>
</main>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</html>

templates/confirmation_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmation Email</title>
</head>
<body>
    <h2>Подтверждение заказа</h2>
    <p>Ваш заказ успешно подтвержден. Спасибо за покупку!</p>
    <p>Номер заказа: {{ order.order_id }}</p>
    <p>Заказ будет доставлен по адресу: {{ order.country }},
        г. {{ order.city }}, ул. {{ order.street }}, д. {{ order.house }}, кв. {{ order.room }}</body>
</html>

templates/order_address.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Order address</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<header class="header">
    <nav class="navigation">
        <div class="info-block d-flex align-items-center flex-row">
            <div class="logo-block"><a href="/" class="logo-link"></a></div>
            <div class="footer-links">
                <a href="#" class="footer-link">О магазине</a>
                <a href="#" class="footer-link">Контакты</a>
            </div>
        </div>
        <div class="links-div d-flex">
            <div class="d-flex align-items-center icon-block">
                <i class="header-basket-icon header-auth"></i>
                {% if user.is_authenticated %}
                    <a class="nav-links" href="/basket/">Корзина</a>
                {% else %}
                    <a class="nav-links" href="/accounts/login">Корзина</a>
                {% endif %}
            </div>
            <div class="d-flex align-items-center icon-block">
                {% if user.is_authenticated %}
                    <i class="header-lk-icon header-auth"></i>
                    <a class="nav-links" href="/profile">Личный кабинет</a>
                {% else %}
                    <i class="header-auth-icon header-auth"></i>
                    <a class="nav-links" href="/accounts/login">Вход / Регистрация</a>
                {% endif %}
            </div>
        </div>
    </nav>
</header>

<main>
    <section>
        <div class="container">
            <h2 class="mb-4">Моя корзина</h2>
            <div class="basket-nav">
                <ul class="ul-basket-nav list-unstyled d-flex flex-row">
                    <li class="li-basket-nav">
                        <span class="nav-icon">1</span>
                        <a href="/basket/" class="a-basket-nav active">Корзина</a>
                    </li>
                    <li class="li-basket-nav">
                        <span class="nav-icon">2</span>
                        <a href="/order-address/" class="a-basket-nav active">Доставка</a>
                    </li>
                    <li class="li-basket-nav">
                        <span class="nav-icon">3</span>
                        <span class="a-basket-nav">Оплата</span>
                    </li>
                    <li class="li-basket-nav">
                        <span class="nav-icon">4</span>
                        <span class="a-basket-nav">Спасибо!</span>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <form method="post" class="d-flex justify-content-center align-items-center flex-column" id="user-update-form">
                {% csrf_token %}
            <div class="main-block">
                 <h3>Адрес доставки</h3>
                <div class="address-info-block d-flex flex-row justify-content-around flex-wrap mb-5">
                    <div class="col-5 mb-3">
                        <label for="id_country" class="form-label"><strong>Страна</strong></label>
                        <input id="id_country" class="form-control me-2 form-control-custom"
                               name="country" type="text"
                               value="{{ user.country }}"
                               placeholder="Страна"
                               aria-label="Страна" maxlength="128" required>
                    </div>
                    <div class="col-5 mb-3">
                        <label for="city" class="form-label"><strong>Город</strong></label>
                        <input id="city" class="form-control me-2 form-control-custom"
                               name="city" type="text"
                               value="{{ user.city }}"
                               placeholder="Город"
                               aria-label="Город" maxlength="128" required>
                    </div>
                    <div class="col-5 mb-3">
                        <label for="street" class="form-label"><strong>Улица</strong></label>
                        <input id="street" class="form-control me-2 form-control-custom"
                               name="street" type="text"
                               value="{{ user.street }}"
                               placeholder="Улица"
                               aria-label="Улица" maxlength="128" required>
                    </div>
                    <div class="col-5 mb-3">
                        <label for="house" class="form-label"><strong>Дом</strong></label>
                        <input id="house" class="form-control me-2 form-control-custom"
                               name="house" type="text"
                               value="{{ user.house }}"
                               placeholder="Дом"
                               aria-label="Дом" maxlength="128" required>
                    </div>
                    <div class="col-5">
                        <label for="room" class="form-label"><strong>Квартира</strong></label>
                        <input id="room" class="form-control me-2 form-control-custom"
                               name="room" type="text"
                               value="{{ user.room }}"
                               placeholder="Квартира" pattern="[0-9]*" title="Введите только цифры"
                               aria-label="Квартира" maxlength="128" required>
                    </div>
                    <div class="col-5">

                    </div>
                </div>
            </div>

                <input class="btn basket-button px-5 col-4 text-center" type="submit" value="Перейти к оплате">
            </form>
        </div>
    </section>
</main>

</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</html>

templates/order_detail.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Order detail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<header class="header">
    <nav class="navigation">
        <div class="info-block d-flex align-items-center flex-row">
            <div class="logo-block"><a href="/" class="logo-link"></a></div>
            <div class="footer-links">
                <a href="#" class="footer-link">О магазине</a>
                <a href="#" class="footer-link">Контакты</a>
            </div>
        </div>
        <div class="links-div d-flex">
            <div class="d-flex align-items-center icon-block">
                <i class="header-basket-icon header-auth"></i>
                {% if user.is_authenticated %}
                    <a class="nav-links" href="/basket/">Корзина</a>
                {% else %}
                    <a class="nav-links" href="/accounts/login">Корзина</a>
                {% endif %}
            </div>
            <div class="d-flex align-items-center icon-block">
                {% if user.is_authenticated %}
                    <i class="header-lk-icon header-auth"></i>
                    <a class="nav-links" href="/profile">Личный кабинет</a>
                {% else %}
                    <i class="header-auth-icon header-auth"></i>
                    <a class="nav-links" href="/accounts/login">Вход / Регистрация</a>
                {% endif %}
            </div>
        </div>
    </nav>
</header>

<main>
    <section>
        <div class="container">
            <h3>Заказ #{{ order.order_id }} от {{ order.nature_date }}</h3>
            {% for item in order_items %}
                <div class="row align-items-center card-custom">
                    <div class="col-md-1">
                        <a href="{% url 'product_detail' product_id=item.goods.order_id %}">
                            <img class="product-image" src="{{ item.goods.image.url }}" alt="Product Image">
                        </a>
                    </div>
                    <div class="col-auto">
                        <span>{{ item.goods.product }}. {{ item.goods.product_description }} </span>
                    </div>
                    <div class="col-auto">
                        <span><strong>{{ item.total_price }} р./{{ item.quantity }} шт</strong></span>
                    </div>
                </div>
            {% endfor %}

            <h4>Заказ будет доставлен по адресу: {{ order.country }},
                г. {{ order.city }}, ул. {{ order.street }}, д. {{ order.house }}, кв. {{ order.room }}
            </h4>
        </div>
    </section>
</main>

</body>
</html>

templates/order_success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>order_success</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<header class="header">
    <nav class="navigation">
        <div class="info-block d-flex align-items-center flex-row">
            <div class="logo-block"><a href="/" class="logo-link"></a></div>
            <div class="footer-links">
                <a href="#" class="footer-link">О магазине</a>
                <a href="#" class="footer-link">Контакты</a>
            </div>
        </div>
        <div class="links-div d-flex">
            <div class="d-flex align-items-center icon-block">
                <i class="header-basket-icon header-auth"></i>
                {% if user.is_authenticated %}
                    <a class="nav-links" href="/basket/">Корзина</a>
                {% else %}
                    <a class="nav-links" href="/accounts/login">Корзина</a>
                {% endif %}
            </div>
            <div class="d-flex align-items-center icon-block">
                {% if user.is_authenticated %}
                    <i class="header-lk-icon header-auth"></i>
                    <a class="nav-links" href="/profile">Личный кабинет</a>
                {% else %}
                    <i class="header-auth-icon header-auth"></i>
                    <a class="nav-links" href="/accounts/login">Вход / Регистрация</a>
                {% endif %}
            </div>
        </div>
    </nav>
</header>

<main>
    <section>
        <div class="container">
            <h2 class="mb-4">Моя корзина</h2>
            <div class="basket-nav">
                <ul class="ul-basket-nav list-unstyled d-flex flex-row">
                    <li class="li-basket-nav">
                        <span class="nav-icon">1</span>
                        <span class="a-basket-nav">Корзина</span>
                    </li>
                    <li class="li-basket-nav">
                        <span class="nav-icon">2</span>
                        <span class="a-basket-nav">Доставка</span>
                    </li>
                    <li class="li-basket-nav">
                        <span class="nav-icon">3</span>
                        <span class="a-basket-nav">Оплата</span>
                    </li>
                    <li class="li-basket-nav">
                        <span class="nav-icon">4</span>
                        <span class="a-basket-nav active">Спасибо!</span>
                    </li>
                </ul>
            </div>
        </div>
    </section>
    
    <section>
        <div class="container">
            <h3>Заказ успешно оплачен!</h3>
            <h5>По адресу  было выслано письмо {{ user.email }} с данными о заказе</h5>
            <h5>Ваш заказ #{{ order.order_id }} от {{ formatted_date }}</h5>
            <h5>Более подробно о заказе можно посмотреть в <a href="{% url 'order_detail' order_id=order.order_id %}">истории заказов</a></h5>
        </div>
    </section>
</main>

</body>
</html>